### ISSUE TITLE
power_generators:shaft_switch freezes minetestserver

### ISSUE THREAD

**Issue by superfloh247** [sfence/power_generators#1] opened 2022-04-13 08:18 UTC
minetestserver latest svn master as of today
power_generators latest svn master as of today

placing a power_generators:shaft_switch between a power_generators:emergency_generator_2 and a power_generators:shaft_hor completely freezes the server.

no error in the logs

2022-04-13 09:41:37: ACTION[Server]: Flo places node power_generators:shaft_switch at (-594,12,593)

Please advise how to produce meaningful debug logs

**Comment by sfence** [comment] 2022-04-13 15:43
Thanks for reporting.
Looks like I am not able to reproduce this bug. Can you give me more informations?

For example screenshots, world files ?
Was generator powered, was shaft_hor powered?

**Comment by superfloh247** [comment] 2022-04-13 20:25
Well, I hope there was power, it was my first experiment with power_generators. I tried to get a ski lift running and followed the screenshots.

Maybe my world is broken, I'll try with a fresh one.

Any chance to enable very verbose logging?

world.mt 
enable_damage = false
creative_mode = false
auth_backend = sqlite3
backend = postgresql
player_backend = sqlite3
gameid = minetest
world_name = yannes
pgsql_connection = host=127.0.0.1 port=5432 user=xxx password=xxx dbname=xxx
load_mod_xocean = true
load_mod_x_farming = true
load_mod_wielded_light = true
load_mod_vehicles = false
load_mod_stonetechnic = false
load_mod_quartzmese = false
load_mod_octu = false
load_mod_condensed = false
load_mod_compressed = false
load_mod_bluecheese = false
load_mod_bakedeye = false
load_mod_throwing = false
load_mod_techpack_warehouse = false
load_mod_techpack_stairway = true
load_mod_safer_lua = false
load_mod_underch = false
load_mod_gravelsieve = true
load_mod_wrench = false
load_mod_technic_chests = true
load_mod_technic = true
load_mod_extranodes = false
load_mod_tubelib_addons2 = true
load_mod_concrete = true
load_mod_subcommands = false
load_mod_spacecannon = false
load_mod_spacesuit = false
load_mod_space_planets = false
load_mod_lcdlib = false
load_mod_space = false
load_mod_skinsdb = true
load_mod_sailing = false
load_mod_rocks = false
load_mod_rocket = false
load_mod_rangedweapons = true
load_mod_pos_marker = false
load_mod_player_monoids = false
load_mod_youngtrees = false
load_mod_woodsoils = false
load_mod_vines = true
load_mod_space_moon = false
load_mod_poisonivy = false
load_mod_molehills = false
load_mod_smartline = false
load_mod_junglegrass = false
load_mod_cavestuff = false
load_mod_pkarcs_doors3 = true
load_mod_pkarcs_doors = true
load_mod_regional_weather = false
load_mod_petz = true
load_mod_mokapi = true
load_mod_paleotest = false
load_mod_obsidianstuff = true
load_mod_nssm = false
load_mod_nativevillages = false
load_mod_multiskin = false
load_mod_moreores = true
load_mod_morelights_modern = false
load_mod_morelights = false
load_mod_modlib = false
load_mod_pipeworks = true
load_mod_cleaner = true
load_mod_mobs_turtles = false
load_mod_bushes = false
load_mod_mobs_sharks = false
load_mod_mobs_jellyfish = false
load_mod_mobs_fish = false
load_mod_mobs_mc = false
load_mod_signs_bot = true
load_mod_mobkit = true
load_mod_mob_core = true
load_mod_moretrees = false
load_mod_moarmour = false
load_mod_hovercraft_ad = true
load_mod_doc_items = true
load_mod_toolranks = false
load_mod_moretrains_vintage = false
load_mod_sl_controller = false
load_mod_pkarcs = false
load_mod_nether = true
load_mod_moretrains_japan = false
load_mod_moretrains_industrial = false
load_mod_moretrains_basic = false
load_mod_moremesecons_pressureplates = false
load_mod_moremesecons_mesecondecorblocks = false
load_mod_mobs_crocs = false
load_mod_moremesecons_dispenser = false
load_mod_tubelib = true
load_mod_minetest-envelopes = false
load_mod_minecart = false
load_mod_mg_villages = false
load_mod_metrosigns = false
load_mod_mesecons_carts = true
load_mod_mesecons_wires = true
load_mod_mesecons_solarpanel = false
load_mod_mesecons_pressureplates = true
load_mod_mesecons_powerplant = true
load_mod_snowball = false
load_mod_mesecons_pistons = true
load_mod_mesecons_mvps = true
load_mod_mesecons_movestones = true
load_mod_mesecons_luacontroller = true
load_mod_mesecons_insulated = true
load_mod_mesecons_hydroturbine = false
load_mod_mesecons_fpga = false
load_mod_homedecor_furniture = false
load_mod_mesecons_doors = true
load_mod_mesecons_detector = true
load_mod_mesecons_alias = false
load_mod_tubelib2 = true
load_mod_castle_weapons = false
load_mod_homedecor_electronics = false
load_mod_mesecons = true
load_mod_mask = false
load_mod_bridger = true
load_mod_mcl_copper = false
load_mod_ambience = false
load_mod_mcl_util = false
load_mod_other_worlds = false
load_mod_maple = false
load_mod_lumberjack = true
load_mod_steles = false
load_mod_livingnether = false
load_mod_lightning = false
load_mod_invisibility = false
load_mod_inbox = false
load_mod_homedecor_windows_and_treatments = false
load_mod_water_life = true
load_mod_jacaranda = false
load_mod_homedecor_tables = false
load_mod_mesecons_materials = true
load_mod_homedecor_roofing = false
load_mod_homedecor_pictures_and_paintings = false
load_mod_homedecor_office = false
load_mod_moresnow = false
load_mod_mesecons_random = true
load_mod_islands = false
load_mod_mesecons_extrawires = true
load_mod_homedecor_lighting = false
load_mod_homedecor_laundry = false
load_mod_meseportals = false
load_mod_homedecor_gastronomy = false
load_mod_stonemese = false
load_mod_doc = true
load_mod_homedecor_fences = false
load_mod_homedecor_electrical = false
load_mod_homedecor_cobweb = false
load_mod_homedecor_clocks = false
load_mod_algae = false
load_mod_homedecor_climate_control = false
load_mod_homedecor_bedroom = false
load_mod_playerphysics = false
load_mod_mesecons_stickyblocks = true
load_mod_ontime_clocks = false
load_mod_homedecor_bathroom = true
load_mod_homedecor_3d_extras = false
load_mod_lightstaff = false
load_mod_building_blocks = true
load_mod_bridgetool = false
load_mod_homedecor_doors_and_gates = true
load_mod_dryplants = false
load_mod_headanim = false
load_mod_x_bows = true
load_mod_homedecor_exterior = false
load_mod_grappling_hook = false
load_mod_3dmushrooms = false
load_mod_footprints = true
load_mod_qa_block = false
load_mod_nether_mobs = false
load_mod_fireworks_redo = false
load_mod_morelights_extras = false
load_mod_mob_horse = false
load_mod_plasmascreen = false
load_mod_farming_flood = true
load_mod_farming = true
load_mod_fachwerk = false
load_mod_ethereal = true
load_mod_homedecor_books = false
load_mod_emeraldbank = false
load_mod_doors = true
load_mod_gravelcraft = false
load_mod_dmobs = false
load_mod_gemtools = false
load_mod_ebony = false
load_mod_dlxtrains_cargo = false
load_mod_dlxtrains = false
load_mod_homedecor_wardrobe = false
load_mod_pomegranate = false
load_mod_signs_road = false
load_mod_advtrains_train_subway = false
load_mod_locks = false
load_mod_mobs_animal = true
load_mod_lib_mount = true
load_mod_mobs = true
load_mod_signs_api = false
load_mod_signs = false
load_mod_mesecons_walllever = true
load_mod_animalia = true
load_mod_ilights = false
load_mod_regrow = false
load_mod_font_metro = false
load_mod_lavalamp = false
load_mod_cottages = false
load_mod_boards = false
load_mod_homedecor_kitchen = false
load_mod_clementinetree = false
load_mod_glider = true
load_mod_3d_armor_stand = true
load_mod_advtrains_train_japan = false
load_mod_digtron = false
load_mod_i3 = false
load_mod_slime_cans = false
load_mod_realcompass = false
load_mod_hopper = false
load_mod_crops = false
load_mod_guinea_pig = true
load_mod_3d_armor_flyswim = false
load_mod_witches = false
load_mod_pineapple = false
load_mod_mahogany = false
load_mod_beautiflowers = false
load_mod_people = false
load_mod_birch = false
load_mod_mesecons_receiver = true
load_mod_bike = true
load_mod_character_anim = false
load_mod_baldcypress = false
load_mod_palm = false
load_mod_font_api = false
load_mod_inventorybags = false
load_mod_clothing = true
load_mod_moretrains_gondola = false
load_mod_cg_plus = false
load_mod_portalgun = false
load_mod_homedecor_furniture_medieval = false
load_mod_keyevent = false
load_mod_auroras = false
load_mod_builtin_item = true
load_mod_mesecons_button = true
load_mod_mcl_chests = false
load_mod_chestnuttree = false
load_mod_basic_materials = true
load_mod_advtrains_line_automation = false
load_mod_nitroglycerine = false
load_mod_tubelib_addons3 = true
load_mod_morelights_vintage = false
load_mod_display_api = false
load_mod_3d_armor_sfinv = true
load_mod_bouncy_bed = false
load_mod_gemenergy = false
load_mod_catchballs = false
load_mod_homedecor_common = true
load_mod_boost_cart = false
load_mod_bonemeal = true
load_mod_mesecons_microcontroller = true
load_mod_mcl_raw_ores = false
load_mod_boats = false
load_mod_biome_lib = true
load_mod_cartographer_minetest_game = false
load_mod_mcl_deepslate = false
load_mod_adv_weapons = false
load_mod_stairs = true
load_mod_slingshot = false
load_mod_advtrains_train_steam = false
load_mod_advtrains_train_industrial = false
load_mod_mesecons_gates = true
load_mod_homedecor_trash_cans = false
load_mod_cmi = false
load_mod_advtrains_train_track = false
load_mod_wieldview = true
load_mod_cacaotree = false
load_mod_kartcar = true
load_mod_mesecons_lamp = true
load_mod_aquaz = true
load_mod_appliances = true
load_mod_uchutechnic = false
load_mod_worldedit = false
load_mod_itemframes = true
load_mod_compost = true
load_mod_mcl_guard_dog = false
load_mod_tt = false
load_mod_goblins = false
load_mod_scifi_nodes = true
load_mod_alchemy = false
load_mod_unifiedbricks = false
load_mod_tuber_honey = false
load_mod_trunks = false
load_mod_mesecons_torch = true
load_mod_fake_fire = false
load_mod_willow = false
load_mod_plumtree = false
load_mod_gardens = false
load_mod_technic_cnc = true
load_mod_lemontree = false
load_mod_gates_long = false
load_mod_motorboat = true
load_mod_bamboo = false
load_mod_tt_base = false
load_mod_biofuel = true
load_mod_3d_plants = false
load_mod_tubelib_addons1 = true
load_mod_advtrains_platform = false
load_mod_serialize_lib = false
load_mod_mesecons_commandblock = false
load_mod_mesecons_lightstone = true
load_mod_advtrains_assets = false
load_mod_gs_amethyst = true
load_mod_larch = false
load_mod_homedecor_misc = false
load_mod_advtrains_signals_ks = false
load_mod_shields = true
load_mod_along_shore = false
load_mod_mobs_monster = false
load_mod_animalworld = true
load_mod_new_campfire = false
load_mod_climate_api = false
load_mod_advtrains_luaautomation = false
load_mod_currency = false
load_mod_doc_basics = false
load_mod_agriculture = false
load_mod_worldedit_shortcommands = false
load_mod_mesecons_switch = true
load_mod_greek = false
load_mod_worldedit_brush = false
load_mod_mesecons_blinkyplant = true
load_mod_denseores = false
load_mod_bows = true
load_mod_moon_phases = false
load_mod_aurora_tech = true
load_mod_luxury_decor = false
load_mod_draconis = false
load_mod_flowers_plus = false
load_mod_worldedit_commands = false
load_mod_froststaff = false
load_mod_handle_schematics = false
load_mod_mesecons_noteblock = false
load_mod_3d_armor = true
load_mod_gs_sapphire = true
load_mod_bushes_classic = false
load_mod_oak = false
load_mod_gs_ruby = true
load_mod_dlxtrains_industrial_wagons = false
load_mod_advtrains_itrainmap = false
load_mod_homedecor_foyer = false
load_mod_gs_emerald = true
load_mod_xdecor = true
load_mod_hyperloop = false
load_mod_hedges = false
load_mod_extra_biomes = false
load_mod_advtrains_interlocking = false
load_mod_homedecor_seating = false
load_mod_cherrytree = false
load_mod_moretrains_steam = false
load_mod_3d_armor_ip = false
load_mod_3d_armor_ui = false
load_mod_doc_identifier = true
load_mod_hollytree = false
load_mod_nature_classic = false
load_mod_ferns = false
load_mod_chesttools = false
load_mod_unifieddyes = true
load_mod_mesecons_delayer = true
load_mod_cartographer = false
load_mod_advtrains = false
load_mod_bale = false
load_mod_worldedit_gui = false
load_mod_motorbike = false
load_mod_mcl_bubble_column = false
load_mod_mcl_shields = false
load_mod_mcl_morefood = false
load_mod_orbs_of_time = true
load_mod_moreblocks = true
load_mod_facade = true
load_mod_anvil = true
load_mod_technic_worldgen = true
load_mod_tmw_slimes = true
load_mod_quartz = true
load_mod_computers = true
load_mod_home_workshop_machines = false
load_mod_home_workshop_common = false
load_mod_home_workshop_misc = false
load_mod_ski = true
load_mod_beacons = true
load_mod_towercrane = true
load_mod_tubelib_tweaks = true
load_mod_large_slugs = true
load_mod_flowerpot = true
load_mod_entity_modifier = true
load_mod_ropes = true
load_mod_lavastuff = true
load_mod_rainbow_ore = true
load_mod_mychisel = true
load_mod_rope_bridges = true
load_mod_adv_lightsabers = true
load_mod_composting = true
load_mod_spyglass = true
load_mod_wings = true
load_mod_jetpack = false
load_mod_flyingcarpet = false
load_mod_dlxtrains_support_wagons = false
load_mod_playereffects = true
load_mod_lwscratch = false
load_mod_lwdrops = false
load_mod_palisade = true
load_mod_portaltest = true
load_mod_halloween = false
load_mod_mcl_blackstone = false
load_mod_mcl_more_ore_variants = false
load_mod_mcl_nether_gold = false
load_mod_mcl_spyglass = false
load_mod_mcl_glass_doors = false
load_mod_wildflower_fields = true
load_mod_mc_warped_fungus_stick = false
load_mod_mc_tridents = false
load_mod_mc_stripped_logs = false
load_mod_mc_scaffolding = false
load_mod_mc_core = false
load_mod_mc_conduits = false
load_mod_mc_campfire = false
load_mod_mc_bamboo = false
load_mod_extra_mobs = false
load_mod_mc_honey = false
load_mod_mcl_mushroom = false
load_mod_mc_ocean = false
load_mod_mc_netherite = false
load_mod_mc_sweet_berry = false
load_mod_moretools = true
load_mod_supercub = false
load_mod_steel = false
load_mod_sponge = true
load_mod_power_generators = true
load_mod_pl_waterlilies = true
load_mod_pl_seaweed = true
load_mod_moretrains_nightline = false
load_mod_death_cetro = false
load_mod_colored_concrete = true
load_mod_blox = false
load_mod_dynamic_liquid = false
load_mod_farming_nextgen = true
load_mod_home_vending_machines = false
load_mod_hidden_doors = true
load_mod_tnt_revamped = true
load_mod_rainf = true
load_mod_sequoia = true
load_mod_redw = true
load_mod_lwcolorable = false
load_mod_pl_sunflowers = true
load_mod_alien_material = true
load_mod_my_sliding_doors = true
load_mod_my_saloon_doors = true
load_mod_my_old_doors = true
load_mod_my_misc_doors = true
load_mod_my_garage_door = true
load_mod_my_fancy_doors = true
load_mod_my_default_doors = false
load_mod_my_future_doors = true
load_mod_my_castle_doors = true
load_mod_my_hidden_doors = false
load_mod_my_door_wood = true
load_mod_my_cottage_doors = true
load_mod_vehicle_mash = true
load_mod_terumet = true
load_mod_terumet-git = false
load_mod_dlxtrains_diesel_locomotives = false
load_mod_digilines = true
load_mod_models = false
load_mod_inventory_plus = false
load_mod_player_model = true
load_mod_python_locale_tool = false
load_mod_creatura = true
load_mod_technic_cnc_improve = true
load_mod_homedecor_plasmascreen = false
load_mod_homedecor_inbox = false
load_mod_tpr = false
load_mod_stoneworks = false
load_mod_mtc_chisel = false
load_mod_travelnet = false
load_mod_minitram_crafting_recipes = false
load_mod_advtrains_attachment_offset_patch = false
load_mod_screenshots = false
load_mod_minitram_konstal_105 = false
load_mod_visual_line_number_displays = false
load_mod_multi_component_liveries = false
load_mod_LICENSES = false
load_mod_minitram_konstal_105_liveries = false
load_mod_chair_lift = true
load_mod_sfinv = false
load_mod_unified_inventory = true
load_mod_unified_inventory_plus = true

**Comment by sfence** [comment] 2022-04-14 02:17
If you are getting mods from repositories, have you updated appliances mod (and clothing/composting)?

**Comment by superfloh247** [comment] 2022-04-14 13:03
all mods are latest master as of now

minimal new world with just

creative_mode = true
load_mod_unified_inventory = true
load_mod_tubelib2 = true
load_mod_biofuel = true
load_mod_chair_lift = true
load_mod_basic_materials = true
load_mod_unified_inventory_plus = true
load_mod_appliances = true
load_mod_power_generators = true

does not freeze. so I'm really sorry, false alarm, my test world seems to be broken, too much testing and adding/removing mods I guess.

I'm too stupid to get the ski lift running
![screenshot_20220414_145906](https://user-images.githubusercontent.com/26180993/163395686-21737ab7-fa4e-474f-a708-85e24437bbd7.png)

two 150 EU generators filled with biofuel "producing" connected to the junction box, connected to the motor. 

punching the motor switches the motor between waiting and unpowered.

**Comment by sfence** [comment] 2022-04-14 14:38
This was caused by a bug in power_generators.
Should be fixed now.
Update mod or try punch to the junction box.

**Comment by sfence** [comment] 2022-04-14 14:42
The problem in your big world can be caused by some mod collision.
After it starts to work in your test world, you can try starting to enable other mods until it breaks.

PS: electric engine can be powered from technic LV as well.

**Comment by superfloh247** [comment] 2022-04-14 16:54
OK, I'm getting there. now the cabin runs for about 3 blocks and stops again.

**Comment by sfence** [comment] 2022-04-14 17:09
The friction is too big for the motor. So, try to use the gearbox to reduce rpm and lower friction on the engine side.
It is a good idea to grease all greaseable parts too (including the engine).

**Comment by superfloh247** [comment] 2022-04-14 17:10
![screenshot_20220414_190936](https://user-images.githubusercontent.com/26180993/163439265-151216b1-1986-42b2-b63e-1cc1fc23343b.png)
![screenshot_20220414_190939](https://user-images.githubusercontent.com/26180993/163439289-ad897a95-c133-4b9a-b687-9964ac4618c2.png)
![screenshot_20220414_190941](https://user-images.githubusercontent.com/26180993/163439295-01d517ba-e576-4e2f-813b-7f4a4e6fad8a.png)
![screenshot_20220414_190945](https://user-images.githubusercontent.com/26180993/163439303-99d3d1f9-d8fe-4d66-ad56-d0544f1aef3f.png)
![screenshot_20220414_190948](https://user-images.githubusercontent.com/26180993/163439308-bd79447e-4a5f-4bdd-b2d8-679baa1c8d9f.png)
![screenshot_20220414_190950](https://user-images.githubusercontent.com/26180993/163439310-29bdb905-608c-493a-a4c6-7a49fc7eb1be.png)

**Comment by superfloh247** [comment] 2022-04-14 17:16
With gearbox it runs for a few seconds, then stops again
![screenshot_20220414_191523](https://user-images.githubusercontent.com/26180993/163440188-c5037504-78c0-4819-8186-589dda3dc4dd.png)
![screenshot_20220414_191528](https://user-images.githubusercontent.com/26180993/163440192-781e95e9-43d6-44ac-bc18-71c18f988536.png)
![screenshot_20220414_191531](https://user-images.githubusercontent.com/26180993/163440196-4a4b4602-adee-41aa-8fc8-f79ffd779eef.png)

**Comment by sfence** [comment] 2022-04-14 17:19
Good. Try hemp oil to grease it, or you can try to combine more engines to power it.

**Comment by superfloh247** [comment] 2022-04-14 17:38
Three motors, gearboxes 1:6

works :)

thanks a lot
![screenshot_20220414_193604](https://user-images.githubusercontent.com/26180993/163443242-c049c7c5-592a-4c98-b8b3-ca51d6339fb8.png)
![screenshot_20220414_193607](https://user-images.githubusercontent.com/26180993/163443262-383fa9d4-b704-4aa7-9c67-63d39c028d75.png)
![screenshot_20220414_193610](https://user-images.githubusercontent.com/26180993/163443269-f8309f65-eb40-4cc0-9d96-467d6c91ef11.png)
![screenshot_20220414_193613](https://user-images.githubusercontent.com/26180993/163443278-f15243d8-0de2-4181-948f-7cc85a95c110.png)
![screenshot_20220414_193617](https://user-images.githubusercontent.com/26180993/163443288-ae4206c6-c3cb-426f-978b-8a0052106477.png)

**Closed as completed** 2022-07-05 15:20 UTC
